services:
  karno-fm-email-poc:
    build: .
    container_name: karno-fm-email-poc
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
