services:
  bluebird-fm-email-poc:
    build: .
    container_name: bluebird-fm-email-poc
    ports:
      - "3050:3000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
